"""
LUT discovery and application.

Two slots are kept independently so a Color-Space-Transform LUT (e.g. S-Log3
to Rec.709) can stack with a creative Look LUT (e.g. Kodak 2383). Both are
applied via mpv's `lut3d` video filter using tetrahedral interpolation —
preferred over trilinear for log source material because it preserves
saturation in the upper highlights.

Folder layout (relative to project root):
    luts/conversions/   generated by lut_generator.py (Sony S-Log3 -> ...)
    luts/cinematic/     bundled MIT-licensed film emulations (YahiaAngelo)
    luts/user/          empty by default; drop your own .cube files here

A LUT is just `{name: str, path: Path, category: str}`.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LUTS_ROOT = PROJECT_ROOT / "luts"

# Categories the UI cares about; ordering = display order.
CATEGORIES = ("conversions", "cinematic", "user")
LUT_EXTS = (".cube", ".3dl")


@dataclass(frozen=True)
class Lut:
    name: str          # display name
    path: Path         # absolute path on disk
    category: str      # one of CATEGORIES


def _humanize(filename: str) -> str:
    """Turn a stem like 'kodak_portra_400_plus' into 'Kodak Portra 400 Plus'."""
    stem = Path(filename).stem
    # Sony's machine-style names like 'SLog3_SGamut3Cine_to_Rec709' deserve
    # a separate cleanup pass.
    s = stem.replace("_", " ").replace("-", " ").replace("plus", "+")
    # Title-case but keep all-caps tokens (Rec.709, DCI, P3, etc.) intact.
    parts = []
    for word in s.split():
        if word.upper() in ("REC", "DCI", "P3", "BT", "HDR", "SDR", "PQ", "HLG", "OLED"):
            parts.append(word.upper())
        elif word in ("Slog3", "Sgamut3cine"):
            parts.append("S-Log3" if word == "Slog3" else "S-Gamut3.Cine")
        else:
            parts.append(word.title())
    return " ".join(parts).replace("Slog3", "S-Log3")


def discover() -> dict[str, list[Lut]]:
    """Scan luts/ and return categorized lists. Missing folders are tolerated."""
    out: dict[str, list[Lut]] = {c: [] for c in CATEGORIES}
    if not LUTS_ROOT.is_dir():
        return out
    for category in CATEGORIES:
        folder = LUTS_ROOT / category
        if not folder.is_dir():
            continue
        files = sorted(
            (p for p in folder.iterdir()
             if p.is_file() and p.suffix.lower() in LUT_EXTS),
            key=lambda p: p.name.lower(),
        )
        for p in files:
            out[category].append(Lut(name=_humanize(p.name), path=p, category=category))
    return out


def apply_to(player, *, cst: Path | None, look: Path | None) -> None:
    """Apply the active LUT to mpv via the `lut` property (GPU pipeline).
    Single-slot for now: when both CST and Look are set, CST wins. True
    stacking would require composing the two .cube files into one.

    Order of property writes matters: set `lut-type` BEFORE `lut`, otherwise
    mpv loads the LUT under whatever type was previously set and may not
    re-evaluate when the type changes.

    Two slots stack as a vf chain in this order:
       source -> CST -> Look -> display
    The CST takes the source colour space (e.g. S-Log3 / S-Gamut3.Cine) into
    the Look's expected input space (Rec.709 for the bundled film LUTs).
    Without CST first, applying a Rec.709-input creative LUT to S-Log3 pixels
    looks wrong (over-saturated, crushed shadows).

    Filters use the `vf` command (not property-set, which rejects strings on
    this libmpv build) and a labelled name (@playercst / @playerlook) so each
    slot can be replaced or cleared independently."""
    sys.stderr.write(f"[luts] applying cst={cst} look={look}\n")

    for path in (cst, look):
        if path is not None and not Path(path).is_file():
            sys.stderr.write(f"[luts] file does NOT exist: {path}\n")
            raise FileNotFoundError(path)

    # Clear our previous filters. `remove` errors silently when label absent.
    for label in ("@playercst", "@playerlook"):
        try:
            player.command("vf", "remove", label)
        except Exception:
            pass

    # Belt-and-suspenders: also clear the lut property in case a previous
    # version of this code set it and left it stuck.
    try:
        player["lut"] = ""
    except Exception:
        pass

    def _append(label: str, path: Path) -> None:
        path_str = str(path).replace("\\", "/")
        filter_str = f"{label}:lut3d=file='{path_str}':interp=tetrahedral"
        player.command("vf", "append", filter_str)
        sys.stderr.write(f"[luts] vf append OK: {filter_str}\n")

    if cst is not None:
        _append("@playercst", cst)
    if look is not None:
        _append("@playerlook", look)

    if cst is None and look is None:
        sys.stderr.write("[luts] chain empty\n")


def clear(player) -> None:
    apply_to(player, cst=None, look=None)
