"""
LUT discovery and application.

Two slots are kept independently so a Color-Space-Transform LUT (e.g. S-Log3
to Rec.709) can stack with a creative Look LUT (e.g. Kodak 2383). Both are
applied via mpv's `lut3d` video filter using tetrahedral interpolation —
preferred over trilinear for log source material because it preserves
saturation in the upper highlights.

Folder layout (relative to project root):
    luts/conversions/   generated by lut_generator.py (Sony S-Log3 -> ...)
    luts/cinematic/     bundled MIT-licensed film emulations (YahiaAngelo)
    luts/user/          empty by default; drop your own .cube files here

A LUT is just `{name: str, path: Path, category: str}`.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LUTS_ROOT = PROJECT_ROOT / "luts"

# Categories the UI cares about; ordering = display order.
CATEGORIES = ("conversions", "cinematic", "user")
LUT_EXTS = (".cube", ".3dl")


@dataclass(frozen=True)
class Lut:
    name: str          # display name
    path: Path         # absolute path on disk
    category: str      # one of CATEGORIES


def _humanize(filename: str) -> str:
    """Turn a stem like 'kodak_portra_400_plus' into 'Kodak Portra 400 Plus'."""
    stem = Path(filename).stem
    # Sony's machine-style names like 'SLog3_SGamut3Cine_to_Rec709' deserve
    # a separate cleanup pass.
    s = stem.replace("_", " ").replace("-", " ").replace("plus", "+")
    # Title-case but keep all-caps tokens (Rec.709, DCI, P3, etc.) intact.
    parts = []
    for word in s.split():
        if word.upper() in ("REC", "DCI", "P3", "BT", "HDR", "SDR", "PQ", "HLG", "OLED"):
            parts.append(word.upper())
        elif word in ("Slog3", "Sgamut3cine"):
            parts.append("S-Log3" if word == "Slog3" else "S-Gamut3.Cine")
        else:
            parts.append(word.title())
    return " ".join(parts).replace("Slog3", "S-Log3")


def discover() -> dict[str, list[Lut]]:
    """Scan luts/ and return categorized lists. Missing folders are tolerated."""
    out: dict[str, list[Lut]] = {c: [] for c in CATEGORIES}
    if not LUTS_ROOT.is_dir():
        return out
    for category in CATEGORIES:
        folder = LUTS_ROOT / category
        if not folder.is_dir():
            continue
        files = sorted(
            (p for p in folder.iterdir()
             if p.is_file() and p.suffix.lower() in LUT_EXTS),
            key=lambda p: p.name.lower(),
        )
        for p in files:
            out[category].append(Lut(name=_humanize(p.name), path=p, category=category))
    return out


def apply_to(player, *, cst: Path | None, look: Path | None) -> None:
    """Apply the active LUT to mpv via the `lut` property (GPU pipeline).
    Single-slot for now: when both CST and Look are set, CST wins. True
    stacking would require composing the two .cube files into one.

    Order of property writes matters: set `lut-type` BEFORE `lut`, otherwise
    mpv loads the LUT under whatever type was previously set and may not
    re-evaluate when the type changes.

    Implementation: we drop the LUT into the video filter chain via the
    `vf` command (NOT the `vf` property — property-set rejects the string
    form on this libmpv build). The labelled filter `@playerlut:...` makes
    it easy to remove on switch/clear.

    The path is single-quoted in the filter argument so the colon in `C:/`
    doesn't get parsed as a filter-arg separator."""
    active = cst if cst is not None else look
    sys.stderr.write(f"[luts] applying: {active}\n")

    if active is not None and not Path(active).is_file():
        sys.stderr.write(f"[luts] file does NOT exist: {active}\n")
        raise FileNotFoundError(active)

    # Clear any previous LUT we installed. `remove` errors if the label
    # isn't there — that's fine on first call.
    try:
        player.command("vf", "remove", "@playerlut")
        sys.stderr.write("[luts] removed previous @playerlut\n")
    except Exception:
        pass

    # Also clear the `lut` property in case an older build of this code set
    # it; otherwise we'd double-apply.
    try:
        player["lut"] = ""
    except Exception:
        pass

    if active is None:
        sys.stderr.write("[luts] no active LUT, chain is now empty\n")
        return

    path_str = str(active).replace("\\", "/")
    filter_str = f"@playerlut:lut3d=file='{path_str}':interp=tetrahedral"
    try:
        player.command("vf", "append", filter_str)
        sys.stderr.write(f"[luts] vf append OK: {filter_str}\n")
    except Exception as e:
        sys.stderr.write(f"[luts] vf append failed: {type(e).__name__}: {e}\n")
        raise


def clear(player) -> None:
    apply_to(player, cst=None, look=None)
